import type { PageSeoEntry } from '@/types';

/**
 * Central Page SEO Registry
 * 
 * Every public route in the application has a dedicated SEO configuration entry here.
 * When you are ready to input researched keywords, fill in `primaryKeyword`, `secondaryKeywords`,
 * and optionally adjust `title`, `description`, or OpenGraph fields for each page below.
 */
export const pageSeoRegistry: Record<string, PageSeoEntry> = {
  home: {
    path: '/',
    title: 'Global Logistics Company & Freight Forwarding Services | SkyLink Global',
    description:
      'SkyLink Global is a leading global logistics company providing international shipping, ocean & air freight forwarding, customs clearance, and supply chain solutions.',
    primaryKeyword: 'global logistics company',
    secondaryKeywords: [
      'international logistics company',
      'freight forwarding services',
      'freight forwarding company',
      'international shipping services',
      'global logistics solutions',
      'logistics and supply chain solutions',
      'air freight services',
      'ocean freight services',
      'sea freight services',
      'customs clearance services',
      'cargo transportation services',
      'import export logistics',
      'end-to-end logistics services',
      'multimodal transportation services',
      'logistics company',
      'logistics services',
      'logistics provider',
      'freight forwarding',
      'shipping company',
      'supply chain management and logistics',
      '3pl logistics',
      'cargo freight forwarders',
      'cargo transportation',
      'international logistics',
      'warehousing',
    ],
    keywords: [
      'global logistics company',
      'international logistics company',
      'freight forwarding services',
      'freight forwarding company',
      'international shipping services',
      'global logistics solutions',
      'logistics and supply chain solutions',
      'air freight services',
      'ocean freight services',
      'sea freight services',
      'customs clearance services',
      'cargo transportation services',
      'import export logistics',
      'end-to-end logistics services',
      'multimodal transportation services',
      'logistics company',
      'logistics services',
      'logistics provider',
      'freight forwarding',
      'shipping company',
      'supply chain management and logistics',
      '3pl logistics',
      'cargo freight forwarders',
      'cargo transportation',
      'international logistics',
      'warehousing',
    ],
    ogTitle: 'SkyLink Global | Premier B2B Logistics Company & Freight Forwarding',
    ogDescription:
      'Connecting global markets with end-to-end logistics services, international freight forwarding, cargo transportation, customs clearance, and warehousing solutions.',
  },


  about: {
    path: '/about',
    title: 'About SkyLink Global | Global Logistics Company & Supply Chain Partner',
    description:
      'SkyLink Global is a premier global logistics company providing international shipping, overseas logistics, freight forwarding, and global supply chain management.',
    primaryKeyword: 'global logistics company',
    secondaryKeywords: [
      'international logistics company',
      'global logistics',
      'global logistics solutions',
      'global logistics services',
      'international shipping company',
      'international freight forwarding company',
      'global supply chain management',
      'global transportation',
      'overseas logistics',
    ],
    keywords: [
      'global logistics company',
      'international logistics company',
      'global logistics',
      'global logistics solutions',
      'global logistics services',
      'international shipping company',
      'international freight forwarding company',
      'global supply chain management',
      'global transportation',
      'overseas logistics',
    ],
    ogTitle: 'About SkyLink Global | Global Logistics Company & Supply Chain Partner',
    ogDescription:
      'SkyLink Global is a premier global logistics company providing international shipping, overseas logistics, freight forwarding, and global supply chain management.',
  },

  aboutOverview: {
    path: '/about/overview',
    title: 'Corporate Overview & Governance | SkyLink Global Services',
    description:
      'Learn about SkyLink Global Services leadership, global infrastructure, trade compliance standards, and our vision for streamlined international commerce.',
    primaryKeyword: 'global supply chain management',
    secondaryKeywords: [
      'international logistics company',
      'global trade operations',
      'EXIM consultancy',
      'statutory trade compliance',
      'multimodal freight logistics',
      'cross-border trade facilitation',
      'global logistics partner',
      'international trade execution',
    ],
    keywords: [
      'global supply chain management',
      'international logistics company',
      'global trade operations',
      'EXIM consultancy',
      'statutory trade compliance',
      'multimodal freight logistics',
      'cross-border trade facilitation',
      'global logistics partner',
      'international trade execution',
    ],
  },

  whySkyLinkAdvantage: {
    path: '/why-choose-us/skylink-advantage',
    title: 'The SkyLink Advantage | Leading Global Logistics Company & Freight Forwarder',
    description:
      'Discover why enterprises choose SkyLink Global: a premier international logistics company delivering global logistics solutions and freight forwarding services.',
    primaryKeyword: 'global logistics solutions',
    secondaryKeywords: [
      'global logistics company',
      'international freight forwarding',
      'freight forwarding company',
      'global logistics',
      'freight forwarding service',
      'global transportation',
      'overseas logistics',
      'international logistics company',
      'global logistics services',
    ],
    keywords: [
      'global logistics solutions',
      'global logistics company',
      'international freight forwarding',
      'freight forwarding company',
      'global logistics',
      'freight forwarding service',
      'global transportation',
      'overseas logistics',
      'international logistics company',
      'global logistics services',
    ],
    ogTitle: 'The SkyLink Advantage | Leading Global Logistics Company & Freight Forwarder',
    ogDescription:
      'Discover why enterprises choose SkyLink Global: a premier international logistics company delivering global logistics solutions and freight forwarding services.',
  },

  whyTraditionalVsSkyLink: {
    path: '/why-choose-us/traditional-vs-skylink',
    title: 'Traditional Logistics vs SkyLink | Customs Clearance & Freight Forwarding Benchmark',
    description:
      'Compare traditional forwarding with SkyLink Global: expert customs clearance services, import export consulting, fast-track customs house agent services, and compliance.',
    primaryKeyword: 'customs clearance',
    secondaryKeywords: [
      'import export consulting',
      'customs clearance services',
      'import export consulting services',
      'customs and clearing agents',
      'customs house agent services',
      'import customs clearance',
      'freight customs clearance',
      'export compliance services',
      'customs clearance and freight forwarding',
    ],
    keywords: [
      'customs clearance',
      'import export consulting',
      'customs clearance services',
      'import export consulting services',
      'customs and clearing agents',
      'customs house agent services',
      'import customs clearance',
      'freight customs clearance',
      'export compliance services',
      'customs clearance and freight forwarding',
    ],
    ogTitle: 'Traditional Logistics vs SkyLink | Customs Clearance & Freight Forwarding Benchmark',
    ogDescription:
      'Compare traditional forwarding with SkyLink Global: expert customs clearance services, import export consulting, fast-track customs house agent services, and compliance.',
  },

  services: {
    path: '/services',
    canonical: '/services',
    title: 'EXIM & Global Logistics Services Portfolio | SkyLink Global Services',
    description:
      'Explore SkyLink Global comprehensive services: international freight forwarding, customs brokerage, bonded warehousing, cold-chain solutions, and trade compliance.',
    primaryKeyword: 'EXIM Consultancy & Global Logistics Services',
    secondaryKeywords: [
      'international freight forwarding services',
      'customs clearance services',
      'cold chain logistics',
      'warehousing solutions',
      'export documentation',
      'marine insurance',
      'trade risk management',
      'end-to-end logistics solutions',
      'global supply chain solutions',
    ],
    keywords: [
      'EXIM Consultancy & Global Logistics Services',
      'international freight forwarding services',
      'customs clearance services',
      'cold chain logistics',
      'warehousing solutions',
      'export documentation',
      'marine insurance',
      'trade risk management',
      'end-to-end logistics solutions',
      'global supply chain solutions',
    ],
  },

  servicesLogisticsShipping: {
    path: '/services/logistics-shipping',
    title: 'International Freight Forwarding Services',
    description:
      'SkyLink Global provides international freight forwarding services across ocean and air freight, multimodal transportation, and real-time shipment tracking.',
    primaryKeyword: 'International Freight Forwarding Services',
    secondaryKeywords: [
      'Freight Forwarding Services',
      'Ocean Freight Services',
      'Air Freight Services',
      'Road Freight Services',
      'Multimodal Transportation',
      'End-to-End Logistics Solutions',
      'Global Supply Chain Solutions',
      'Cargo Transportation Services',
      'Customs Clearance Support',
      'Shipment Tracking and Visibility',
    ],
    keywords: [
      'International Freight Forwarding Services',
      'Freight Forwarding Services',
      'Ocean Freight Services',
      'Air Freight Services',
      'Road Freight Services',
      'Multimodal Transportation',
      'End-to-End Logistics Solutions',
      'Global Supply Chain Solutions',
      'Cargo Transportation Services',
      'Customs Clearance Support',
      'Shipment Tracking and Visibility',
      'international shipping services',
      'global freight forwarding',
      'multimodal shipping',
    ],
    ogTitle: 'International Freight Forwarding Services | SkyLink Global',
    ogDescription:
      'End-to-end logistics solutions connecting global trade lanes with ocean freight, air freight services, road transport, and real-time shipment tracking.',
  },

  servicesColdChainSolutions: {
    path: '/services/cold-chain-solutions',
    title: 'Cold Chain Logistics & Solutions',
    description:
      'SkyLink Global provides cold chain logistics and temperature controlled logistics, including cold chain transportation, cold chain monitoring, and pharmaceutical logistics.',
    primaryKeyword: 'cold chain logistics',
    secondaryKeywords: [
      'cold chain solutions',
      'temperature controlled logistics',
      'cold chain transportation',
      'pharmaceutical logistics',
      'cold chain monitoring',
      'cold storage transport',
      'cold chain supply chain',
      'pharmaceutical cold chain logistics',
      'cold storage and distribution',
    ],
    keywords: [
      'cold chain logistics',
      'cold chain solutions',
      'temperature controlled logistics',
      'cold chain transportation',
      'pharmaceutical logistics',
      'cold chain monitoring',
      'cold storage transport',
      'cold chain supply chain',
      'pharmaceutical cold chain logistics',
      'cold storage and distribution',
    ],
    ogTitle: 'Cold Chain Logistics & Solutions | SkyLink Global',
    ogDescription:
      'Temperature controlled logistics, cold chain transportation, and pharmaceutical cold chain logistics with active cold chain monitoring and refrigerated distribution.',
  },

  servicesWarehousingSolutions: {
    path: '/services/warehousing-solutions',
    title: 'Warehousing Solutions for Exporters',
    description:
      'SkyLink Global delivers warehousing solutions and warehouse storage: bonded warehouse facilities, WMS inventory management, and export warehouse logistics.',
    primaryKeyword: 'warehousing solutions',
    secondaryKeywords: [
      'warehousing',
      'inventory management',
      'wms',
      'warehouse logistics',
      'warehouse management',
      'bonded warehouse',
      'warehouse management system',
      'warehouse storage',
      'warehousing and logistics',
    ],
    keywords: [
      'warehousing',
      'inventory management',
      'wms',
      'warehouse logistics',
      'warehouse management',
      'bonded warehouse',
      'warehouse management system',
      'warehouse storage',
      'warehousing and logistics',
      'warehousing solutions',
    ],
    ogTitle: 'Warehousing Solutions for Exporters | SkyLink Global',
    ogDescription:
      'Strategic warehousing and logistics for exporters: bonded warehouse storage, WMS inventory management, and export warehouse logistics.',
  },

  servicesWarehousingDistribution: {
    path: '/services/warehousing-distribution',
    canonical: '/services/warehousing-solutions',
    title: 'Warehousing Solutions for Exporters',
    description:
      'SkyLink Global delivers warehousing solutions and warehouse storage: bonded warehouse facilities, WMS inventory management, and export warehouse logistics.',
    primaryKeyword: 'warehousing solutions',
    secondaryKeywords: [
      'warehousing',
      'inventory management',
      'wms',
      'warehouse logistics',
      'warehouse management',
      'bonded warehouse',
      'warehouse management system',
      'warehouse storage',
      'warehousing and logistics',
    ],
    keywords: [
      'warehousing',
      'inventory management',
      'wms',
      'warehouse logistics',
      'warehouse management',
      'bonded warehouse',
      'warehouse management system',
      'warehouse storage',
      'warehousing and logistics',
      'warehousing solutions',
    ],
    ogTitle: 'Warehousing Solutions for Exporters | SkyLink Global',
    ogDescription:
      'Strategic warehousing and logistics for exporters: bonded warehouse storage, WMS inventory management, and export warehouse logistics.',
  },

  servicesDocumentationLiaison: {
    path: '/services/documentation-liaison',
    title: 'Export Documentation & Shipping Documentation',
    description:
      'SkyLink Global delivers export documentation and shipping documentation: commercial invoice, shipping bill, bill of entry, and certificate of origin filing.',
    primaryKeyword: 'export documentation',
    secondaryKeywords: [
      'shipping bill',
      'bill of lading',
      'iec code',
      'bill of entry',
      'icegate shipping bill',
      'commercial invoice',
      'certificate of origin',
      'import export documentation',
      'shipping documentation',
    ],
    keywords: [
      'shipping bill',
      'bill of lading',
      'iec code',
      'bill of entry',
      'icegate shipping bill',
      'export documentation',
      'commercial invoice',
      'certificate of origin',
      'import export documentation',
      'shipping documentation',
    ],
    ogTitle: 'Export Documentation & Shipping Documentation | SkyLink Global',
    ogDescription:
      'Comprehensive export documentation and shipping documentation: commercial invoices, shipping bills, bill of entry, and certificate of origin.',
  },

  servicesTaxGstCompliance: {
    path: '/services/tax-gst-compliance',
    title: 'Customs Clearance Services',
    description:
      'SkyLink Global delivers customs clearance services, import customs clearance, customs declaration support, and trade compliance services for global shipments.',
    primaryKeyword: 'Customs Clearance Services',
    secondaryKeywords: [
      'Customs Clearance',
      'Customs Declaration',
      'Customs Documentation',
      'Import Customs Clearance',
      'Import Export Customs Clearance',
      'Customs Compliance Services',
      'Trade Compliance Services',
      'Import Export Compliance',
      'Customs Clearance Support',
    ],
    keywords: [
      'Customs Clearance Services',
      'Customs Clearance',
      'Customs Declaration',
      'Customs Documentation',
      'Import Customs Clearance',
      'Import Export Customs Clearance',
      'Customs Compliance Services',
      'Trade Compliance Services',
      'Import Export Compliance',
      'Customs Clearance Support',
      'GST advisory',
      'LUT filing',
      'ITC reconciliation',
    ],
    ogTitle: 'Customs Clearance Services | SkyLink Global',
    ogDescription:
      'Comprehensive customs clearance services, import export customs documentation, LUT filing advisory, and trade compliance services for global trade.',
  },

  servicesTaxGstAdvisory: {
    path: '/services/tax-gst-advisory',
    canonical: '/services/tax-gst-compliance',
    title: 'Customs Clearance Services',
    description:
      'SkyLink Global delivers customs clearance services, import customs clearance, customs declaration support, and trade compliance services for global shipments.',
    primaryKeyword: 'Customs Clearance Services',
    secondaryKeywords: [
      'Customs Clearance',
      'Customs Declaration',
      'Customs Documentation',
      'Import Customs Clearance',
      'Import Export Customs Clearance',
      'Customs Compliance Services',
      'Trade Compliance Services',
      'Import Export Compliance',
      'Customs Clearance Support',
    ],
    keywords: [
      'Customs Clearance Services',
      'Customs Clearance',
      'Customs Declaration',
      'Customs Documentation',
      'Import Customs Clearance',
      'Import Export Customs Clearance',
      'Customs Compliance Services',
      'Trade Compliance Services',
      'Import Export Compliance',
      'Customs Clearance Support',
    ],
    ogTitle: 'Customs Clearance Services | SkyLink Global',
    ogDescription:
      'Comprehensive customs clearance services, import export customs documentation, LUT filing advisory, and trade compliance services for global trade.',
  },

  servicesRiskManagement: {
    path: '/services/risk-management',
    title: 'Risk Management in Exports | Marine Insurance',
    description:
      'SkyLink Global delivers trade risk management for exporters: marine cargo insurance, export insurance, freight insurance, and proactive contingency planning.',
    primaryKeyword: 'marine insurance',
    secondaryKeywords: [
      'contingency planning',
      'trade risk management',
      'marine cargo insurance',
      'cargo insurance',
      'export insurance',
      'freight insurance',
      'export credit insurance',
      'shipment insurance',
      'marine transit insurance',
      'cargo insurance coverage',
      'freight insurance coverage',
      'export credit guarantee corporation',
      'export risk management',
    ],
    keywords: [
      'marine insurance',
      'contingency planning',
      'trade risk management',
      'marine cargo insurance',
      'cargo insurance',
      'export insurance',
      'freight insurance',
      'export credit insurance',
      'shipment insurance',
      'marine transit insurance',
      'cargo insurance coverage',
      'freight insurance coverage',
      'export credit guarantee corporation',
      'export risk management',
    ],
    ogTitle: 'Risk Management in Exports: Marine Insurance & Advisory | SkyLink Global',
    ogDescription:
      'Comprehensive trade risk management: marine cargo insurance, export credit insurance, contingency planning, and claims settlement support.',
  },

  servicesTradeRiskManagement: {
    path: '/services/trade-risk-management',
    canonical: '/services/risk-management',
    title: 'Risk Management in Exports | Marine Insurance',
    description:
      'SkyLink Global delivers trade risk management for exporters: marine cargo insurance, export insurance, freight insurance, and proactive contingency planning.',
    primaryKeyword: 'marine insurance',
    secondaryKeywords: [
      'contingency planning',
      'trade risk management',
      'marine cargo insurance',
      'cargo insurance',
      'export insurance',
      'freight insurance',
      'export credit insurance',
      'shipment insurance',
      'marine transit insurance',
      'cargo insurance coverage',
      'freight insurance coverage',
      'export credit guarantee corporation',
      'export risk management',
    ],
    keywords: [
      'marine insurance',
      'contingency planning',
      'trade risk management',
      'marine cargo insurance',
      'cargo insurance',
      'export insurance',
      'freight insurance',
      'export credit insurance',
      'shipment insurance',
      'marine transit insurance',
      'cargo insurance coverage',
      'freight insurance coverage',
      'export credit guarantee corporation',
      'export risk management',
    ],
    ogTitle: 'Risk Management in Exports: Marine Insurance & Advisory | SkyLink Global',
    ogDescription:
      'Comprehensive trade risk management: marine cargo insurance, export credit insurance, contingency planning, and claims settlement support.',
  },

  industries: {
    path: '/industries',
    title: 'Industry Solutions | Specialized EXIM & Logistics Support',
    description:
      'Tailored trade logistics and regulatory compliance frameworks for pharmaceuticals, seafood & aquaculture, specialty chemicals, agro-fertilizers, and perishables.',
    primaryKeyword: 'Industry Logistics Solutions',
    secondaryKeywords: [
      'Specialized Industry Logistics',
      'Pharma Cold Chain Logistics',
      'Seafood Export Logistics',
      'Specialty Chemicals Logistics',
      'Automotive Logistics',
      'Engineering Project Cargo',
      'Textiles Export Logistics',
      'Agro Commodity Logistics',
      'Hazmat Transportation Services',
    ],
    keywords: [
      'Industry Logistics Solutions',
      'Specialized Industry Logistics',
      'Pharma Cold Chain Logistics',
      'Seafood Export Logistics',
      'Specialty Chemicals Logistics',
      'Automotive Logistics',
      'Engineering Project Cargo',
      'Textiles Export Logistics',
      'Agro Commodity Logistics',
      'Hazmat Transportation Services',
    ],
  },

  industriesPharma: {
    path: '/industries/pharma',
    title: 'Pharmaceutical EXIM & Cold Chain Logistics | SkyLink Global Services',
    description:
      'GDP-compliant cold chain logistics, temperature-controlled air & ocean freight, and expedited customs clearance for pharmaceutical exports.',
    primaryKeyword: 'Pharmaceutical Cold Chain Logistics',
    secondaryKeywords: [
      'Pharma Logistics',
      'GDP Compliant Logistics',
      'Temperature Controlled Logistics',
      'Pharma Air Freight',
      'Reefer Shipping for Pharmaceuticals',
      'Vaccine Logistics',
      'Life Science Logistics',
      'ADC Customs Clearance',
      'Pharma Supply Chain',
    ],
    keywords: [
      'Pharmaceutical Cold Chain Logistics',
      'Pharma Logistics',
      'GDP Compliant Logistics',
      'Temperature Controlled Logistics',
      'Pharma Air Freight',
      'Reefer Shipping for Pharmaceuticals',
      'Vaccine Logistics',
      'Life Science Logistics',
      'ADC Customs Clearance',
      'Pharma Supply Chain',
    ],
  },

  industriesSeafoods: {
    path: '/industries/seafoods',
    title: 'Seafood & Marine Products Export Logistics | SkyLink Global Services',
    description:
      'Ultra-low temperature reefer container management, MPEDA documentation, EIA health certification, and rapid green-channel customs clearance for seafood exports.',
    primaryKeyword: 'Seafood Export Logistics',
    secondaryKeywords: [
      'Marine Products Cold Chain',
      'Reefer Container Shipping',
      'Sub-Zero Cold Chain',
      'MPEDA Compliance Logistics',
      'EIA Health Certification Liaison',
      'Frozen Fish Shipping',
      'Shrimp Export Logistics',
      'Port Cold Storage Transport',
    ],
    keywords: [
      'Seafood Export Logistics',
      'Marine Products Cold Chain',
      'Reefer Container Shipping',
      'Sub-Zero Cold Chain',
      'MPEDA Compliance Logistics',
      'EIA Health Certification Liaison',
      'Frozen Fish Shipping',
      'Shrimp Export Logistics',
      'Port Cold Storage Transport',
    ],
  },

  industriesChemicalsAgro: {
    path: '/industries/specialty-chemicals-agro-fertilizers-perishables',
    title: 'Specialty Chemicals, Agro-Fertilizers & Perishables Logistics | SkyLink Global',
    description:
      'Hazchem handling (IMDG code), fertilizer movement regulatory support, and humidity-controlled transit for perishable agro-commodities.',
    primaryKeyword: 'Specialty Chemicals & Agro Logistics',
    secondaryKeywords: [
      'Hazmat Chemical Logistics',
      'IMDG Dangerous Goods Forwarding',
      'ISO Tank Container Logistics',
      'Controlled Atmosphere Reefer Shipping',
      'APEDA Trade Compliance',
      'Phytosanitary Certification Logistics',
      'Perishable Cargo Logistics',
      'Chemical Supply Chain Management',
    ],
    keywords: [
      'Specialty Chemicals & Agro Logistics',
      'Hazmat Chemical Logistics',
      'IMDG Dangerous Goods Forwarding',
      'ISO Tank Container Logistics',
      'Controlled Atmosphere Reefer Shipping',
      'APEDA Trade Compliance',
      'Phytosanitary Certification Logistics',
      'Perishable Cargo Logistics',
      'Chemical Supply Chain Management',
    ],
  },

  sustainabilityAeoGreen: {
    path: '/sustainability/aeo-green',
    canonical: '/sustainability/aeo-green',
    title: 'Authorized Economic Operator & AEO Certification | SkyLink Global',
    description:
      'Explore Authorized Economic Operator services, AEO certification, AEO compliance, AEO customs clearance, paperless customs clearance and AEO Green Channel benefits with SkyLink Global.',
    primaryKeyword: 'Authorized Economic Operator',
    secondaryKeywords: [
      'AEO Certification',
      'AEO Cert',
      'Authorized Economic Operator AEO',
      'AEO Accreditation',
      'AEO Certification India',
      'AEO Compliance',
      'AEO Customs Clearance',
      'Paperless Customs Clearance',
      'AEO Accredited',
      'AEO Authorization',
      'AEO Certification Benefits',
      'AEO Certification Requirements',
      'AEO Customs Certification',
      'AEO Green Channel',
    ],
    keywords: [
      'Authorized Economic Operator',
      'AEO Certification',
      'AEO Cert',
      'Authorized Economic Operator AEO',
      'AEO Accreditation',
      'AEO Certification India',
      'AEO Compliance',
      'AEO Customs Clearance',
      'Paperless Customs Clearance',
      'AEO Accredited',
      'AEO Authorization',
      'AEO Certification Benefits',
      'AEO Certification Requirements',
      'AEO Customs Certification',
      'AEO Green Channel',
    ],
    ogTitle: 'Authorized Economic Operator & AEO Certification | SkyLink Global',
    ogDescription:
      'Explore Authorized Economic Operator services, AEO certification, AEO compliance, AEO customs clearance, paperless customs clearance and AEO Green Channel benefits with SkyLink Global.',
  },

  sustainabilityEcoRoute: {
    path: '/sustainability/eco-route',
    canonical: '/sustainability/eco-route',
    title: 'Multimodal Transportation & Sustainable Logistics Solutions | SkyLink Global',
    description:
      'Discover multimodal transportation, sustainable logistics, green logistics, low carbon logistics and sustainable supply chain solutions with SkyLink Global’s Eco-Route services.',
    primaryKeyword: 'Multimodal Transportation',
    secondaryKeywords: [
      'Sustainable Logistics',
      'Green Logistics',
      'Sustainable Supply Chain',
      'Sustainable Supply Chain Management',
      'Green Supply Chain Management',
      'Multimodal Logistics',
      'Low Carbon Logistics',
      'Eco Friendly Logistics',
      'Supply Chain Carbon Footprint',
    ],
    keywords: [
      'Multimodal Transportation',
      'Sustainable Logistics',
      'Green Logistics',
      'Sustainable Supply Chain',
      'Sustainable Supply Chain Management',
      'Green Supply Chain Management',
      'Multimodal Logistics',
      'Low Carbon Logistics',
      'Eco Friendly Logistics',
      'Supply Chain Carbon Footprint',
    ],
    ogTitle: 'Multimodal Transportation & Sustainable Logistics Solutions | SkyLink Global',
    ogDescription:
      'Discover multimodal transportation, sustainable logistics, green logistics, low carbon logistics and sustainable supply chain solutions with SkyLink Global’s Eco-Route services.',
  },

  collaborateFreightForwarders: {
    path: '/collaborate/freight-forwarders',
    title: 'Freight Forwarder Collaboration | International Freight Forwarding Services',
    description:
      'Partner with SkyLink Global: connect your freight forwarding company with steady enterprise cargo logistics, trade lane allocations, and competitive rates.',
    primaryKeyword: 'freight forwarding services',
    secondaryKeywords: [
      'freight forwarding company',
      'international freight forwarding',
      'cargo logistics',
      'cargo forwarding services',
      'freight and forwarding companies',
      'international freight forwarding companies',
      'international freight forwarding services',
      'logistics and freight forwarding',
      'shipping and freight forwarding',
    ],
    keywords: [
      'freight forwarding services',
      'freight forwarding company',
      'international freight forwarding',
      'cargo logistics',
      'cargo forwarding services',
      'freight and forwarding companies',
      'international freight forwarding companies',
      'international freight forwarding services',
      'logistics and freight forwarding',
      'shipping and freight forwarding',
    ],
    ogTitle: 'Freight Forwarder Collaboration | International Freight Forwarding Services',
    ogDescription:
      'Partner with SkyLink Global: connect your freight forwarding company with steady enterprise cargo logistics, trade lane allocations, and competitive rates.',
  },

  collaborateEnquiry: {
    path: '/collaborate/enquiry',
    title: 'Freight Forwarder Collaboration Enquiry | SkyLink Global Services',
    description:
      'Connect with our global alliances desk to explore freight forwarding partnerships, agency agreements, and cross-border trade cooperation.',
    primaryKeyword: 'freight forwarder partnership',
    secondaryKeywords: [
      'freight forwarding agency',
      'logistics collaboration enquiry',
      'international freight agency',
      'freight agent offer submission',
      'global freight forwarding network',
    ],
    keywords: [
      'freight forwarder partnership',
      'freight forwarding agency',
      'logistics collaboration enquiry',
      'international freight agency',
      'freight agent offer submission',
      'global freight forwarding network',
    ],
  },

  newsBlogs: {
    path: '/news/blogs',
    canonical: '/news/blogs',
    title: 'International Shipping News & Maritime Industry Updates | SkyLink Global',
    description:
      'Read international shipping news, world maritime news, IMO 2023 regulations, IMO GHG emissions strategy, MEPC 76, MEPC 79 and global shipping industry updates from SkyLink Global.',
    primaryKeyword: 'International Shipping News',
    secondaryKeywords: [
      'World Maritime News',
      'World Shipping News',
      'International Maritime News',
      'International Shipping Industry',
      'IMO 2023 Regulation',
      'IMO GHG Emissions Strategy',
      'IMO MEPC 76',
      'MEPC 79 IMO',
      'International Chamber of Shipping',
    ],
    keywords: [
      'International Shipping News',
      'World Maritime News',
      'World Shipping News',
      'International Maritime News',
      'International Shipping Industry',
      'IMO 2023 Regulation',
      'IMO GHG Emissions Strategy',
      'IMO MEPC 76',
      'MEPC 79 IMO',
      'International Chamber of Shipping',
    ],
    ogTitle: 'International Shipping News & Maritime Industry Updates | SkyLink Global',
    ogDescription:
      'Read international shipping news, world maritime news, IMO 2023 regulations, IMO GHG emissions strategy, MEPC 76, MEPC 79 and global shipping industry updates from SkyLink Global.',
  },

  newsArticles: {
    path: '/news/articles',
    title: 'Trade Intelligence & Industry Articles | SkyLink Global Services',
    description:
      'In-depth whitepapers and articles covering customs tariff revisions, supply chain resilience, free trade agreements, and global market dynamics.',
    primaryKeyword: 'international trade compliance',
    secondaryKeywords: [
      'customs regulations',
      'trade intelligence articles',
      'tariff revision updates',
      'EXIM whitepapers',
      'free trade agreement advisory',
    ],
    keywords: [
      'international trade compliance',
      'customs regulations',
      'trade intelligence articles',
      'tariff revision updates',
      'EXIM whitepapers',
      'free trade agreement advisory',
    ],
  },

  blog: {
    path: '/blog',
    canonical: '/blog',
    title: 'International Shipping News & Maritime Industry Updates | SkyLink Global',
    description:
      'Read international shipping news, world maritime news, IMO 2023 regulations, IMO GHG emissions strategy, MEPC 76, MEPC 79 and global shipping industry updates from SkyLink Global.',
    primaryKeyword: 'International Shipping News',
    secondaryKeywords: [
      'World Maritime News',
      'World Shipping News',
      'International Maritime News',
      'International Shipping Industry',
      'IMO 2023 Regulation',
      'IMO GHG Emissions Strategy',
      'IMO MEPC 76',
      'MEPC 79 IMO',
      'International Chamber of Shipping',
    ],
    keywords: [
      'International Shipping News',
      'World Maritime News',
      'World Shipping News',
      'International Maritime News',
      'International Shipping Industry',
      'IMO 2023 Regulation',
      'IMO GHG Emissions Strategy',
      'IMO MEPC 76',
      'MEPC 79 IMO',
      'International Chamber of Shipping',
    ],
    ogTitle: 'International Shipping News & Maritime Industry Updates | SkyLink Global',
    ogDescription:
      'Read international shipping news, world maritime news, IMO 2023 regulations, IMO GHG emissions strategy, MEPC 76, MEPC 79 and global shipping industry updates from SkyLink Global.',
  },

  contact: {
    path: '/contact',
    title: 'Contact SkyLink Global Services | B2B Trade & Logistics Advisory',
    description:
      'Get in touch with our global trade advisory team. Schedule a consultation or reach our offices in India for freight, customs, and compliance support.',
    primaryKeyword: 'trade advisory services',
    secondaryKeywords: [
      'logistics consultancy contact',
      'customs clearance consultation',
      'freight forwarding office',
      'EXIM advisory team',
      'international shipping enquiry',
    ],
    keywords: [
      'trade advisory services',
      'logistics consultancy contact',
      'customs clearance consultation',
      'freight forwarding office',
      'EXIM advisory team',
      'international shipping enquiry',
    ],
  },

  requestConsultation: {
    path: '/request-consultation',
    title: 'Request an EXIM Consultation & Freight Quote | SkyLink Global Services',
    description:
      'Submit your shipment parameters or trade compliance requirements to receive a customized strategic advisory proposal from our specialists.',
    primaryKeyword: 'EXIM consultation',
    secondaryKeywords: [
      'freight quote request',
      'customs compliance consultation',
      'international trade advisory proposal',
      'cargo logistics consultation',
      'supply chain advisory',
    ],
    keywords: [
      'EXIM consultation',
      'freight quote request',
      'customs compliance consultation',
      'international trade advisory proposal',
      'cargo logistics consultation',
      'supply chain advisory',
    ],
  },

  brand: {
    path: '/brand',
    title: 'Brand Identity & Assets | SkyLink Global Services',
    description:
      'Official brand assets, typography, color systems, and corporate identity guidelines for SkyLink Global Services.',
    primaryKeyword: 'SkyLink Global brand identity',
    secondaryKeywords: [
      'corporate brand assets',
      'logistics brand guidelines',
      'official motion logo',
      'corporate visual identity',
    ],
    keywords: [
      'SkyLink Global brand identity',
      'corporate brand assets',
      'logistics brand guidelines',
      'official motion logo',
      'corporate visual identity',
    ],
  },
};

/**
 * Helper to retrieve page SEO config by registry key
 */
export function getPageSeo(key: keyof typeof pageSeoRegistry | string): PageSeoEntry | undefined {
  return pageSeoRegistry[key];
}

/**
 * Helper to retrieve page SEO config by pathname
 */
export function getPageSeoByPath(path: string): PageSeoEntry | undefined {
  const normalized = path.replace(/\/$/, '') || '/';
  return Object.values(pageSeoRegistry).find((entry) => {
    const entryNormalized = entry.path.replace(/\/$/, '') || '/';
    return entryNormalized === normalized;
  });
}
